# Generated by Django 5.2.5 on 2025-08-29 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=100)),
                ('lname', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price_cents', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded')], default='PAID', max_length=10)),
                ('subtotal_cents', models.IntegerField()),
                ('manual_discount_type', models.CharField(choices=[('NONE', 'None'), ('STUDENT_10', 'Student -10%'), ('FRIENDS_FAMILY_20', 'Friends/Family -20%')], default='NONE', max_length=32)),
                ('manual_discount_cents', models.IntegerField(default=0)),
                ('loyalty_redemption_cents', models.IntegerField(default=0)),
                ('tax_cents', models.IntegerField()),
                ('tip_cents', models.IntegerField(default=0)),
                ('total_cents', models.IntegerField()),
                ('points_earned', models.IntegerField(default=0)),
                ('redeemed_points', models.IntegerField(default=0)),
                ('paid_at', models.DateTimeField()),
                ('receipt_number', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('COMP', 'Comp')], max_length=8)),
                ('refund_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=120)),
                ('unit_price_cents', models.IntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='store.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('COMP', 'Comp')], max_length=8)),
                ('amount_cents', models.IntegerField()),
                ('rounding_cents', models.IntegerField(default=0)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='store.order')),
            ],
        ),
    ]
