# Generated by Django 5.2.5 on 2025-08-31 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_options_category_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['menu_item', 'position'],
            },
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('selection_type', models.CharField(choices=[('SINGLE', 'Single'), ('MULTI', 'Multi')], default='SINGLE', max_length=10)),
                ('min_select', models.PositiveIntegerField(default=0)),
                ('max_select', models.PositiveIntegerField(default=1)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Modifier group',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModifierOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price_delta_cents', models.IntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['group__position', 'group__name', 'position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name_snapshot', models.CharField(max_length=80)),
                ('option_name_snapshot', models.CharField(max_length=80)),
                ('price_delta_cents_snapshot', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('base_price_cents', models.IntegerField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['menu_item', 'position', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category__position', 'position', 'name']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-paid_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='paymentrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='register_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='base_unit_price_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_name_snapshot',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='store.category'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.customer'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paid_at'], name='store_order_paid_at_9b3e55_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='store_order_status_428b25_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_by'], name='store_order_created_a32a80_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='store_order_custome_5796e7_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='store_order_order_i_70b6d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_item_per_category'),
        ),
        migrations.AddField(
            model_name='itemmodifiergroup',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='store.menuitem'),
        ),
        migrations.AddField(
            model_name='itemmodifiergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_items', to='store.modifiergroup'),
        ),
        migrations.AddField(
            model_name='modifieroption',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='store.modifiergroup'),
        ),
        migrations.AddField(
            model_name='orderitemmodifier',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='store.orderitem'),
        ),
        migrations.AddField(
            model_name='variant',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.menuitem'),
        ),
        migrations.AddConstraint(
            model_name='itemmodifiergroup',
            constraint=models.UniqueConstraint(fields=('menu_item', 'group'), name='uniq_group_per_item'),
        ),
        migrations.AddConstraint(
            model_name='modifieroption',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='uniq_option_per_group'),
        ),
        migrations.AddIndex(
            model_name='orderitemmodifier',
            index=models.Index(fields=['order_item'], name='store_order_order_i_fdf392_idx'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('menu_item', 'name'), name='uniq_variant_per_item'),
        ),
    ]
