# Generated by Django 5.2.5 on 2025-09-01 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_itemmodifiergroup_modifiergroup_modifieroption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
