# Generated by Django 5.2.5 on 2025-09-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='base_price_cents',
            new_name='price_cents',
        ),
    ]
