# Generated by Django 5.2.5 on 2025-09-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_base_price_cents_variant_price_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='kind',
            field=models.CharField(choices=[('FOOD', 'Food'), ('DRINK', 'Drink')], default='DRINK', max_length=10),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='applies_to',
            field=models.CharField(choices=[('FOOD', 'Food'), ('DRINK', 'Drink'), ('BOTH', 'Both')], default='BOTH', max_length=10),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='modifier_groups', to='store.category'),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='direct_modifier_groups', to='store.menuitem'),
        ),
    ]
