# Generated by Django 5.2.5 on 2025-09-02 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_menuitem_kind_modifiergroup_applies_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modifieroption',
            old_name='price_delta_cents',
            new_name='price_cents',
        ),
    ]
