# Generated by Django 5.2.6 on 2025-09-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_price_delta_cents_modifieroption_price_cents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position', 'name'], 'permissions': [('manage_categories', 'Can edit categories')]},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('manage_customers', 'Can edit customers')]},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category__position', 'position', 'name'], 'permissions': [('manage_menu_items', 'Can edit items')]},
        ),
        migrations.AlterModelOptions(
            name='modifiergroup',
            options={'ordering': ['position', 'name'], 'permissions': [('manage_modifiers_groups', 'Can edit modifier groups')], 'verbose_name': 'Modifier group'},
        ),
        migrations.AlterModelOptions(
            name='modifieroption',
            options={'ordering': ['group__position', 'group__name', 'position', 'name'], 'permissions': [('manage_modifiers', 'Can edit modifier options')]},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-paid_at', '-id'], 'permissions': [('apply_any_discount', 'Can apply any discount'), ('void_order', 'Can void order'), ('refund_order', 'Can refund order'), ('view_sales_reports', 'Can view sales reports'), ('add order', 'Can add order'), ('change order', 'Can change order'), ('view order', 'Can view order'), ('apply_given_discount', 'Can apply given discount')]},
        ),
        migrations.AlterModelOptions(
            name='paymentrecord',
            options={'ordering': ['-created_at'], 'permissions': [('view_sales_reports', 'Can view sales reports')]},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['menu_item', 'position', 'name'], 'permissions': [('manage_variants', 'Can edit variants')]},
        ),
        migrations.AddField(
            model_name='order',
            name='discount_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='rounding_delta_cents',
            field=models.IntegerField(default=0),
        ),
    ]
