# Generated by Django 5.2.6 on 2025-09-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
