# Generated by Django 5.2.6 on 2025-09-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_paymentrecord_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='static/receipts/'),
        ),
    ]
