# Generated by Django 5.2.6 on 2025-10-13 01:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_internal_notes_order_receipt_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('apply_any_discount', 'Can apply any discount'), ('void_order', 'Can void order'), ('refund_order', 'Can refund order'), ('view_sales_reports', 'Can view sales reports'), ('add order', 'Can add order'), ('change order', 'Can change order'), ('view order', 'Can view order'), ('apply_given_discount', 'Can apply given discount')]},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='store_order_paid_at_9b3e55_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_at',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='store_order_created_4ba192_idx'),
        ),
    ]
