# Generated by Django 5.2.6 on 2025-10-13 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_order_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentRecord',
        ),
    ]
